INSERT INTO users(type, username, full_name, bio, email, phone, password, role, gender, age_group, is_active) VALUES
    ('SUPER_ADMIN',
    'superadmin-test',
    'Superadmin Full Name',
    '',
    'superadmin-test@email.com',
    '+301230000001',
    '$2a$10$tyZhvHRirYBsTclmBZD7WOiD3hmXR0yUsCejVJWkOJ1COU8v42zL2',
    'ROLE_SUPERADMIN',
    'MALE',
    'ADULT',
    TRUE),

    ('ADMIN',
    'admin-test',
    'Admin Full Name',
    '',
    'admin-test@email.com',
    '+301230000002',
    '$2a$10$tyZhvHRirYBsTclmBZD7WOiD3hmXR0yUsCejVJWkOJ1COU8v42zL2',
    'ROLE_ADMIN',
    'FEMALE',
    'ADULT',
    TRUE),

    ('CUSTOMER',
    'customer-test',
    'Customer Full Name',
    '',
    'customer-test@email.com',
    '+301230000003',
    '$2a$10$tyZhvHRirYBsTclmBZD7WOiD3hmXR0yUsCejVJWkOJ1COU8v42zL2',
    'ROLE_CUSTOMER',
    'FEMALE',
    'TEENAGER',
    TRUE),

    ('INSTRUCTOR',
    'instructor-test',
    'Instructor Full Name',
    'Bio instructor',
    'instructor-test@email.com',
    '+301230000004',
    '$2a$10$tyZhvHRirYBsTclmBZD7WOiD3hmXR0yUsCejVJWkOJ1COU8v42zL2',
    'ROLE_INSTRUCTOR',
    'MALE',
    'ADULT',
    TRUE);

--Test password: Password1!
